### ISSUE TITLE
LBA 2.3 code review - Thunder Rahja, June 2022

### ISSUE THREAD

**Issue by ThunderRahja** [Krutchen/SLMCLBA#19]
Dear Dread,

This script as a whole is pretty messy and at times difficult to follow. You can significantly improve its readability by adding whitespace between variables, literals, and operators and by writing more descriptive variable names. If memory becomes a concern, I recommend [PyOptimizer](https://github.com/Sei-Lisa/LSL-PyOptimizer) to equipment developers.

Under the current version numbering scheme, 2.3 implies that it came before 2.22. If you want to change that, I suggest 2.3.0 to start, and refer to current versions retroactively as 2.2.x.

Specific areas for improvement follow.

https://github.com/Krutchen/SLMCLBA/blob/989c7a56df92b5d398e2007fc198191769a16c4d/LBA-v.2.3.lsl#L42-L47 A vehicle moving back and forth between adjacent regions may eventually max out its listener limit and become unable to receive LBA damage messages. Add `llListenRemove(lh)` before 46 to fix this. No error message is thrown for invalid handles given to `llListenRemove`.

https://github.com/Krutchen/SLMCLBA/blob/989c7a56df92b5d398e2007fc198191769a16c4d/LBA-v.2.3.lsl#L81-L84 If an empty list is returned by 81, 84 will be always be false, rendering 82 redundant. Further, if kept, 82 can be shortened to `if(mes)` because an empty list will evaluate as 0, which is equivalent to false.

https://github.com/Krutchen/SLMCLBA/blob/989c7a56df92b5d398e2007fc198191769a16c4d/LBA-v.2.3.lsl#L86-L87 There are many low-effort methods of generating a randomized name. Filtering out one method will cause abusers to simply switch to another. This isn't useful unless the point is to stop outdated and abusive gear from being used.

https://github.com/Krutchen/SLMCLBA/blob/989c7a56df92b5d398e2007fc198191769a16c4d/LBA-v.2.3.lsl#L92-L93 I suggest having these limits as global variables easily found and changed at the top of the script, and provide these values as part of the object description. The minimum of `-20` could limit the potential for a long-charge, burst repair item.

https://github.com/Krutchen/SLMCLBA/blob/989c7a56df92b5d398e2007fc198191769a16c4d/LBA-v.2.3.lsl#L99 Beware that some mesh artists have developed models for multiple different groups and vendors. This opens up to the scenario where the creator gets blacklisted from using an outdated munition and results in every munition other people in the same party (i.e. a grenade) being blocked. Additionally, there is no line that adds `creator` to the blacklist, only `owner`.

https://github.com/Krutchen/SLMCLBA/blob/989c7a56df92b5d398e2007fc198191769a16c4d/LBA-v.2.3.lsl#L130-L132 ~~`llGetObjectDetails(key id, [OBJECT_SCALE])` was added recently and is a more straightforward alternative to checking the bounding box.~~ Hand grenades also usually have a small bounding box like mines.

https://github.com/Krutchen/SLMCLBA/blob/989c7a56df92b5d398e2007fc198191769a16c4d/LBA-v.2.3.lsl#L146-L157 Checking for same-source damage from parent objects is easily bypassed by using an intermediary object that dies when its rezzed child object sends the damage message.

https://github.com/Krutchen/SLMCLBA/blob/989c7a56df92b5d398e2007fc198191769a16c4d/LBA-v.2.3.lsl#L223-L232 What we have here are two separate, locally defined limits on the amount of damage one owner can inflict (as `val`) based on whether or not the damage source is an attached weapon on a standing avatar. While `150` is still a pretty liberal value, it's inconsistent with the limit per single hit of `300` as checked on line 92. This opens up the possibility of an avatar-attached weapon dealing a single hit between 150 and 300 damage and becoming blacklisted on follow-up chip damage, i.e. 5, while still below the 300 cap single hit damage.

https://github.com/Krutchen/SLMCLBA/blob/989c7a56df92b5d398e2007fc198191769a16c4d/LBA-v.2.3.lsl#L262 Don't do this. `llGetRegionTimeDilation` is severely outdated and irrelevant and does not reflect actual script performance. Just keep it to the 1 second timer or you may get unpredictable timings when the region slows down.

https://github.com/Krutchen/SLMCLBA/blob/989c7a56df92b5d398e2007fc198191769a16c4d/LBA-v.2.3.lsl#L272 Replace with `if(proc)`. A list that is empty returns 0, but returns the length of the list otherwise. There are two more places where you used `!=[]`.

Love, Thunder

**Comment by Krutchen** [comment]
" A vehicle moving back and forth between adjacent regions may eventually max out its listener limit and become unable to receive LBA damage messages. Add llListenRemove(lh) before 46 to fix this. No error message is thrown for invalid handles given to llListenRemove."
Yeah good call i'll be on that asap, same with the other efficiency passes. 

"I suggest having these limits as global variables easily found and changed at the top of the script, and provide these values as part of the object description. The minimum of -20 could limit the potential for a long-charge, burst repair item."
These were changed from being easily changeable because people kept on doing dumb stuff with them, 150 for infantry and 300 for vehicles is a good ballpark max that isn't triggering on regular weapons. basic keygen name rejection is to mess with baby grief. 

"Beware that some mesh artists have developed models for multiple different groups and vendors. This opens up to the scenario where the creator gets blacklisted from using an outdated munition and results in every munition other people in the same party (i.e. a grenade) being blocked. Additionally, there is no line that adds creator to the blacklist, only owner."
I'll remove the creator check, really shouldn't be a big thing since the blackbox was removed, this was for longterm tracking of shitbird behaviour.

"llGetObjectDetails(key id, [OBJECT_SCALE]) was added recently and is a more straightforward alternative to checking the bounding box. Hand grenades also usually have a small bounding box like mines."
default
{
    state_entry()
    {
        key targ="56e8e964-3d05-c64d-3ca3-f603fee6a3b4";
        vector scale=llList2Vector(llGetObjectDetails(targ,[OBJECT_SCALE]),0);
        llOwnerSay("My SCALE is "+(string)scale);
        list bb=llGetBoundingBox(targ);
        vector tsize=llList2Vector(bb,1)-llList2Vector(bb,0); 
        llOwnerSay("My BB is "+(string)tsize);
    }
}
[15:51] Object: My SCALE is <2.00000, 2.00000, 2.00000>
[15:51] Object: My BB is <6.10069, 2.50958, 4.41486>
Scale returns dimensions of the root prim and not the total object, sadly. if it returned full bounding box that'd be great.

"Checking for same-source damage from parent objects is easily bypassed by using an intermediary object that dies when its rezzed child object sends the damage message."
If they do that it defaults the source to their avatar key and they essentially get a 150 AT cap, which tends to really cuck attempts at grief. Generally a direct fire weapon hitting you multiple times won't be running these checks due to the shortcut functionality @ line 144
'
                            if(tries)
                            {
                                @srcfind;//Jumps back here for iterations if the check didn't get a valid source
                                key src2=llList2Key(ownerinfo,3);//Src2 is the last rezzer key
                                integer shortcut=llListFindList(recent,[src2]);
                                if(shortcut==-1)
                                { '

"What we have here are two separate, locally defined limits on the amount of damage one owner can inflict (as val) based on whether or not the damage source is an attached weapon on a standing avatar. While 150 is still a pretty liberal value, it's inconsistent with the limit per single hit of 300 as checked on line 92. This opens up the possibility of an avatar-attached weapon dealing a single hit between 150 and 300 damage and becoming blacklisted on follow-up chip damage, i.e. 5, while still below the 300 cap single hit damage."
Line 92 is a "don't try oneshotting me with a shitload of damage" flat cap type of thing, but if someone can output over 300 damage within 4 seconds they're probably trying to grief your vehicle, so that's kind of a "get bent" situation at that point. The only way I could see a shitton of damage like that being legitimately sent through would be mines, which are taken care of on line 128

**Comment by HadetTheUndying** [comment]
Please code highlight you code if possible @Krutchen it makes it hard to tell where the code chunks end and your comments begin. https://www.markdownguide.org/cheat-sheet For code use three ticks instead of just one and at the first set of three ticks you can specify that it's lsl code by adding lsl next to them

**Comment by Krutchen** [comment]
Krutchen — Yesterday at 2:42 PM
https://github.com/Krutchen/SLMCLBA/issues/19
GitHub
[LBA 2.3 code review - Thunder Rahja, June 2022 · Issue #19 · Krutch...](https://github.com/Krutchen/SLMCLBA/issues/19)
Dear Dread, This script as a whole is pretty messy and at times difficult to follow. You can significantly improve its readability by adding whitespace between variables, literals, and operators an...
LBA 2.3 code review - Thunder Rahja, June 2022 · Issue #19 · Krutch...
Did you have any other things on that btw
Thunder Rahja — Yesterday at 2:42 PM
Naw, I looked over the edits and thought they were fine.
Krutchen — Yesterday at 2:42 PM
Fasho
Thunder Rahja — Yesterday at 2:43 PM
Feel free to close it.
