### ISSUE TITLE
AT_CAP bypassing with renaming of the AT delivery prim.

### ISSUE THREAD

**Issue by Sufferot** [Krutchen/SLMCLBA#2]
AT_CAP can be bypassed with basic renaming of the munition. 
Example:
[03:21] Testing bypass: 
Hit by sufferot Resident with '-0.622592' for 66 damage 
Hit by sufferot Resident with '-0.858047' for 56 damage 
Hit by sufferot Resident with '-0.754038' for 61 damage 
Hit by sufferot Resident with '-0.184986' for 55 damage 
Hit by sufferot Resident with '-0.563232' for 51 damage

Should count AT_CAP per person, additionally to per munition.
Same way can be used to bypass the full damage on the thing.
[03:24] Testing bypass no AT limit: 
Hit by sufferot Resident with '-0.104401' for 142 damage 
Hit by sufferot Resident with '-0.145191' for 566 damage 
Hit by sufferot Resident with '-0.742391' for 545 damage 
Hit by sufferot Resident with '-0.951701' for 534 damage 
Hit by sufferot Resident with '-0.168192' for 544 damage

For reference - AT delivery in this metod detects scripted objects and rezzes new AT delivery prim every time it detects it.

**Comment by HadetTheUndying** [comment]
Probably need to change the tracking to get the object key instead of object name.

**Comment by ThunderRahja** [comment]
Object keys are already tracked in `list recent` and additional damage messages from the same prim over a 120 second interval are discarded.

T'koi is known for using random floats as names for their damage prims to obfuscate the source and attempt to prevent it from being filtered by name. Using multiple damage prims to send damage messages within a short window bypasses `atcap` but is prone to cause the user to be blacklisted by `trigger`. Currently, to become blacklisted by `trigger`, all of the following must be met:

- Cumulative damage of all hits by one owner (`tdmg`) exceeds `trigger` in one `timer` event, e.g. one second
- 6 or more hits were taken from that owner in one `timer` event
- The average damage per hit (`dph`) exceeds 5

T'koi is aware of these conditions and designs their weapons to circumvent them. The best way to deal with this issue is to moderate which weapons are allowed in a combat area.

**Comment by HadetTheUndying** [comment]
Would be nice if LL would actually push The Object Rez Time feature through

**Comment by HadetTheUndying** [comment]
Closing until we hear from LL about our feature request.
